### ISSUE TITLE
[BUG] Settings for Zeus

### ISSUE THREAD

**Issue by csportalsk** [CS-GEJMERZY/VIP-Plugin#12]
When you set in config "Zeus": false, you still get Zeus on spawn.
VIP Plugin v1.0.4
CSSharp v195
Linux

**Comment by HackerDevs** [comment]
Thanks for the report. The issue has been fixed in f4c82a80abbf9c8524dbb3891460f20b883d3ec0. 
https://github.com/CS-GEJMERZY/VIP-Plugin/releases/tag/v1.0.5
