### ISSUE TITLE
[REG] Switching guns fix

### ISSUE THREAD

**Issue by csportalsk** [CS-GEJMERZY/VIP-Plugin#15]
Main problem now of plugin is for Retakes or DM server is when you spawned VIP plugin switch gun from primary, to secondary or from secondary to knife. This is very annoying :(

**Comment by HackerDevs** [comment]
Hey, I've changed the way refreshing player UI is done. Please check if the issue is still present in v1.0.10
https://github.com/CS-GEJMERZY/VIP-Plugin/releases/tag/v1.0.10

**Comment by csportalsk** [comment]
Hi, I tested v1.0.10 with CSS v202 and the issue is fixed. Thank you <3
