### ISSUE TITLE
[REQ] Several features

### ISSUE THREAD

**Issue by zyzz1989** [CS-GEJMERZY/VIP-Plugin#16]
- Double jump 
- Healthshot on spawn
- Show damage given 
- Reset score 
- Reserved slot

**Comment by HackerDevs** [comment]
Hi @zyzz1989, thanks for the feature request! 
- **Double jump**: This is already configurable. Check the `ExtraJumps `setting in your config file.
- **Healthshot on spawn:** Great idea! We'll add this to our upcoming features release.
- **Show damage given, Reset score, Reserved slot**: These sound like excellent features, but I think are better suited for a separate plugins. This would help keep the VIP plugin more concise.
