### ISSUE TITLE
[REQ] Colored smoke

### ISSUE THREAD

**Issue by csportalsk** [CS-GEJMERZY/VIP-Plugin#17]
Adding feature for colored smoke will be nice as an option :]
M1Kac have separated plugin, but still doesn't work for flag permission.
https://github.com/M1Kac/Simple-ColoredSmoke/blob/main/Simple%20ColoredSmoke/ColoredSmoke.cs

**Comment by HackerDevs** [comment]
Hey, great idea. This will be added in the feature release.
