### ISSUE TITLE
[FEAT]Add these

### ISSUE THREAD

**Issue by chycken** [CS-GEJMERZY/VIP-Plugin#26]
Hi, is that possible to add these functions?:
- Bhop
- HP regen
- Armor regen
- Instant plant + defuse

**Comment by HackerDevs** [comment]
Hi, thanks for the great suggestions! I'm looking forward to releasing these next week.

**Comment by chycken** [comment]
> Hi, thanks for the great suggestions! I'm looking forward to releasing these next week.

Thanks sir
It'd be awesome if these features were setable, i mean we can set the bhop that it will be able to use after xy sec after the beginning of the round, and we can set how much faster will be the instadefuse/plant
Suggestion : pls share this plugin on CSHARP discord channel: https://discord.gg/eAZU3guKWU

**Comment by HackerDevs** [comment]
- Regarding the fast plant and defuse feature, you'll have the option to configure the timing from the beginning of each round, as well as adjust the speed of planting/defusing
- For health and armor regeneration, parameters will include the amount, interval (every x seconds), and delay (x seconds after the round starts).
- Bunnyhopping will be implemented, although enforcing specific bunnyhopping console variables on a per-client basis is not currently available, as far as I'm aware.

**Comment by chycken** [comment]
> * Regarding the fast plant and defuse feature, you'll have the option to configure the timing from the beginning of each round, as well as adjust the speed of planting/defusing.
> * For health and armor regeneration, config will include the amount, interval (every x seconds), and delay (x seconds after the round starts).
> * Bunnyhopping will be implemented, although enforcing specific bunnyhopping console variables on a per-client basis is not currently available, as far as I'm aware.
> 
> Let me know if you'd like any further customization options for these functions.

great, I tested your plugin in the meantime and compared it with another famous vip plugin (vipcore).
A few more tips:
viptest (!viptest) instead of -randomvip, so if someone enters the command, e.g. You will receive a vip for 20 minutes (a group that we set up), and this command, e.g. allows a player to use it max 2x a week
-if a vip player enters the !vip command, an html menu will appear in which you can see which group you are in / the name of the group (eg smallvip, plusvip) and you can see what functions it has (eg bhop) and you can even select these in the menu you can disable one by one if you don't want one
-16000$ for the vip in every rounds

**Comment by chycken** [comment]
@HackerDevs thanks for the update. Have you thought about my last message?

**Comment by HackerDevs** [comment]
Yes, I'm planning to do the viptest, but to make it happen, I'll likely need to implement database support for VIP. The menu with preferences isn't the most important thing right now, but it's a good suggestion. Removing 16k$ on round should be pretty straightforward. If you want these features added, please make a new request, since this has already been resolved.
