### ISSUE TITLE
[BUG] DefuseKit

### ISSUE THREAD

**Issue by csportalsk** [CS-GEJMERZY/VIP-Plugin#28]
"DefuseKit": true, setting dosn't work.
VIP-Plugin v1.0.21, CSS v202

**Comment by HackerDevs** [comment]
Hello, I've confirmed that DefuseKit is functioning correctly with the following setup: plugins version 1.0.21, alongside CSS v203 and metamod 1282. 

1. Clarify what you mean by _"doesn't work"_. Does it imply receiving a defuse kit when it shouldn't be granted, or the opposite scenario?
2. What metamod version are you running?
3. Were you encountering the issue prior to version 1.0.21?
4. If possible, provide config for the group you're testing.

**Comment by csportalsk** [comment]
1. Players with group doesn't receiving a defuse kit on spaw. On server were more players with granted group. Other VIP functions works normaly. It happened two maps in a row. **Now I was test it again. I was alone on server and I get defuzekit normally.** I will be watching more next days if there is some scenario when players didn't get kit on spawn again.
2. Metamod:Source version 2.0.0-dev+1282
3. No

**Comment by HackerDevs** [comment]
Is the issue still present?

**Comment by csportalsk** [comment]
It didn't happen again ¯\_(ツ)_/¯

**Comment by HackerDevs** [comment]
I'm marking the issue as resolved for now. Should you encounter it again, feel free to reopen or create a new one.
