### ISSUE TITLE
Plugin Error.

### ISSUE THREAD

**Issue by wohahobg** [CS-GEJMERZY/VIP-Plugin#55]
Hi,

I have installed the last version of this plugin but i am getting 

08:14:06 [INFO] (cssharp:PluginContext) Loading plugin VIP-Plugin
[Info] - Trampoline - Bounds of relative addresses accessed [0xffffffffffffffff, (nil)]
[Info] - Trampoline - Attempting to allocate trampoline within +-2GB range of 0x7f1c2802de10
[Info] - Trampoline - Allocated trampoline at 0x7f1ca802c000 (using 1 attempts)
08:14:06 [INFO] (cssharp:PluginContext) Finished loading plugin VIP Plugin

I am using the lasted version of the plugin.

**Comment by HackerDevs** [comment]
Hello, these logs you posted are just debug logs from CounterStrikeSharp. Is the plugin working correctly?

**Comment by HackerDevs** [comment]
Hello, these are just debug logs from CSS hooks.
