### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gha241** [CS-GEJMERZY/VIP-Plugin#56]
[Info] - Trampoline - Bounds of relative addresses accessed [0xffffffffffffffff, (nil)]
[Info] - Trampoline - Attempting to allocate trampoline within +-2GB range of 0x7f9e91257110
[Info] - Trampoline - Allocated trampoline at 0x7f9f11256000 (using 1 attempts)

**Comment by HackerDevs** [comment]
Hello, these are just debug logs from CSS hooks.
