### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gha241** [CS-GEJMERZY/VIP-Plugin#65]
![IMG_20241004_210720](https://github.com/user-attachments/assets/26978aab-481f-4b09-bc58-5d8cdd33d788)

Pls update

**Comment by gha241** [comment]
@HackerDevs @wohahobg

**Comment by HackerDevs** [comment]
Hi, thanks for info. Shoud be fixed in **v1.1.10**. https://github.com/CS-GEJMERZY/VIP-Plugin/releases/tag/v1.1.10

**Comment by gha241** [comment]
Thanks 😁
